### PR TITLE
Add fine print at bottom of form

### PR DESCRIPTION
**Pull request by cmoesel**

### CODE REVIEW

**Comment by rdingwell** [comment]
I think we need to hold off before pulling this in. I'm not sure a reinterpretation of a CDC form still allows us to say it's an OMB approved form

**Comment by cmoesel** [comment]
OK.  I was just following what's in the mockup. ;-)

**Comment by cmoesel** [comment]
Do you think we're OK if we remove:

> Form Approved: OMB: 0920-1011 Exp. 4/23/2020

Or we can just forget about the whole thing.  That would be fine by me.

**Comment by noranda** [comment]
I'd say just leave off the Form Approved text (maybe put a flag in so we can add it easily later) and leave the rest of the text. @rdingwell ?

**Comment by cmoesel** [comment]
Yeah, so... I don't think this is going to ever get merged. Closing it to keep the clutter down.

**Pull request closed without merging**
